### ISSUE TITLE
There's another django-bootstrap

### ISSUE THREAD

**Issue by ericflo** [earle/django-bootstrap#17]
http://pypi.python.org/pypi/django-bootstrap

**Comment by earle** [comment]
Definitely do not care for this type of implementation.

**Comment by ericflo** [comment]
Oh I absolutely agree, I like your approach much better.  I was just letting you know because you unfortunately won't be able to ever upload this to PyPI under this name since it's already taken.  Might it be worth it to rename the project to differentiate the two?

**Comment by blanchardjeremy** [comment]
Agree. You should totally host this on pypi. Might want to rename before you have even more followers than you already do.

**Comment by slafs** [comment]
Maybe this is irrelevant or deserves separate issue but consider joining forces with [django-crispy-forms](https://github.com/maraujop/django-crispy-forms) (a successor of django-uni-form) since it has a bootstrap support already. Disclaimer: i haven't used neither project (I was using django-uni-form though)
