### ISSUE TITLE
Possibility of BootstrapModelForm?

### ISSUE THREAD

**Issue by jaddison** [earle/django-bootstrap#3]
It would be great to have an equivalent Bootstrap ModelForm to work with.  I'm not sure how to approach it - what are your thoughts?

**Comment by bactisme** [comment]
+1

**Comment by earle** [comment]
roger that.  i'll get to this when i have some spare time this weekend hopefully

**Comment by jaddison** [comment]
I'd be more than happy to help test this out with you.

**Comment by earle** [comment]
accidentally had closed this

**Comment by honza** [comment]
:+1: Would love to help if needed, thanks

**Comment by earle** [comment]
Feel free to take a shot at this and send me a Pull Request

**Comment by alexsv** [comment]
|'m thinking how to do it in pythonic way without coping the code, tried to use multi-inheritance without luck

**Comment by BradWhittington** [comment]
Seems like the best approach would be:

class CommonRendererMixin:
    #methods for rendering

class BootstrapForm(forms.Form, CommonRendererMixin):
   # Specifics for normal form

class BootstrapModelForm(forms.Form, CommonRendererMixin):
   # Specifics for model form

If this seems sensible, I can try the approach out when I have some time this week, since I need this class like...yesterday...

**Comment by alexsv** [comment]
Yes, i did something in this approach,
Thought it broke some functionality, but i'm not sure where (we are using wizards)

**Comment by earle** [comment]
Maybe add the mixins as a Meta attribute in the Model itself

**Comment by BradWhittington** [comment]
@earle that doesn't leave a clean separation between model + form creation/rendering, and pushes bootstrap integration even deeper into the app.

**Comment by earle** [comment]
@bradwhittington correct.  using a Model, and a Form abstracts that relationship.  If you're combining a Model, and a Form, I by using a ModelForm, then I dont see why having the attribute configuration in the Model is a big deal -- since any changes to the model are going to potentially require changing to the behavior of how the form is rendered. 

Bootstrap is designed to be a way to highly customize these forms and their behavior in a very stylistic way -- I'm not even sure a ModelForm makes sense anyways, particularly given the handling of the UX elements during rendition

**Comment by earle** [comment]
If someone wants to present a novel solution to a BootstrapModelForm, I'm all ears.
